language: php
php:
  - 7.2
services:
  - mysql
before_script:
  - composer install
script: ./vendor/bin/phpunit ./tests
deploy:
  provider: heroku
  app: anabel-travis-heroku-2
  on: master
  skip_cleanup: true
  api_key: e9337beb-177e-4406-be8f-2e43d7ce70da
